config/routes.rb
Cooperhewitt::Application.routes.draw do


  resource :login, :only => [:show], :controller => 'login'

  resource :callback, :only => [:show], :controller => 'callback'

  resource :search, :only => [:show], :controller => 'search'

  resources :type_of_thing, :path => '', :controller => 'type_of_thing', :only => [:show]

  resource :votes, :only => [:create], :controller => 'votes'

  root :to => 'homepage#show'


end

app/models/thing.rb
class Thing < ActiveRecord::Base
  attr_accessible

  has_many :thingings
  has_many :types_of_thing, :through => :thingings

  scope :with_image, where('image IS NOT NULL')

  def ch_link
    "https://collection.cooperhewitt.org/objects/" + ch_id.to_s + "/"
  end

end

app/models/thinging.rb
class Thinging < ActiveRecord::Base
  attr_accessible

  belongs_to :thing, :counter_cache => :types_count
  belongs_to :type_of_thing, :counter_cache => :things_count

end

app/models/type_of_thing.rb
class TypeOfThing < ActiveRecord::Base
  attr_accessible :ch_id, :name, :things_count

  has_many :thingings
  has_many :things, :through => :thingings


  def self.update_things_with_images_count!

    self.find_each do |type_of_thing|

      type_of_thing.things_with_images_count = type_of_thing.things.with_image.count
      type_of_thing.save

    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController

  def show
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def show
    @example_types = TypeOfThing.where(:things_with_images_count => 6..999999).order('random()').limit(10)
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController


  def show
    client = OAuth2::Client.new('e129d553792a9f1a4237df58321fd911', 'client_secret', :site => 'https://api.collection.cooperhewitt.org/rest/')

    render :text => client.auth_code.authorize_url(:redirect_uri => 'http://localhost:8080/oauth2/callback')
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def show
    redirect_to type_of_thing_path(params[:q])
  end

end

app/controllers/type_of_thing_controller.rb
class TypeOfThingController < ApplicationController

  def show

    type_of_thing_name = params[:id].downcase.singularize

    begin
      @type_of_thing = TypeOfThing.find_by_name!(type_of_thing_name)

      things = @type_of_thing.things.with_image.order('classicness_score DESC')

      @classic_things = things[0..2]

      @other_things = things[3..9999]

    rescue ActiveRecord::RecordNotFound

      @type_of_thing = TypeOfThing.new({:name => type_of_thing_name})
      render 'not_found'
    end

  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create

    @thing = Thing.find(params[:thing_id])
    @type_of_thing = @thing.types_of_thing.first

    if params[:vote] == 'up'
      @thing.classicness_score += 1
    elsif params[:vote] == 'down'
      @thing.classicness_score -= 1
    end

    @thing.save
    render 'show'
#    redirect_to type_of_thing_path(thing_type.name.downcase.pluralize)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/show.html.erb
<article>
  <h1>The Cooper-Hewitt Collection of Design Things</h1>

  <div class="intro call-to-action">Show me the 3 classic

  <form method="GET" action="<%= search_path %>">
    <%= text_field_tag :q, '', :placeholder => 'teapots' %>
  </form>
  .
  </div>

  <p>Examples:

    <% example_links = [] %>

    <% @example_types.each do |type_of_thing| %>
      <% example_links << link_to(type_of_thing.name.pluralize, type_of_thing_path(type_of_thing.name.pluralize.downcase)) %>
    <% end %>
    <%= example_links.to_sentence.html_safe %>
  </p>

</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cooperhewitt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/type_of_thing/not_found.html.erb
<%= link_to "Back", root_path, :class => 'button' %>

<article>
  <h1>Darn, the Cooper-Hewitt doesn't have any <span><%= @type_of_thing.name.pluralize %></span></h1>

  <p class="intro call-to-action">Why not bug their curators to go acquire some?</p>
</article>

app/views/type_of_thing/show.html.erb
<%= link_to "Back", root_path, :class => 'button' %>

<% if @classic_things.size > 0 %>

  <article>
    <h1>The 3 classic <span class="name"><%= @type_of_thing.name.pluralize %></span></h1>

    <div class="things">

      <% @classic_things.each do |thing| %>

        <div class="thing">
          <%= link_to image_tag(thing.image), thing.ch_link %>

          <p><%= link_to thing.name, "https://collection.cooperhewitt.org/objects/#{thing.ch_id}/" %></p>

          <form action="<%= votes_path %>" method="POST">
            <%= hidden_field_tag 'thing_id', thing.id %>
            <%= hidden_field_tag 'vote', 'down' %>
            <button>This isn't that classic!</button>
          </form>

        </div>
      <% end %>
    </div>

    <% if @other_things %>

      <h2>The other <span class="name"><%= @type_of_thing.name.pluralize %></span></h2>

      <div class="other-things">

        <% @other_things.each do |thing| %>

          <div class="thing">
            <%= link_to image_tag(thing.image), thing.ch_link %>

            <p><%= link_to thing.name, "https://collection.cooperhewitt.org/objects/#{thing.ch_id}/" %></p>

            <form action="<%= votes_path %>" method="POST">
              <%= hidden_field_tag 'thing_id', thing.id %>
              <%= hidden_field_tag 'vote', 'up' %>
              <button>This is more classic!</button>
            </form>

          </div>
        <% end %>
      </div>
    <% end %>
  </article>

<% else %>

  <article>
    <h1>Darn, the Cooper-Hewitt has some <span class="name"><%= @type_of_thing.name.pluralize %></span>, but it hasn't take any photos of them yet.</h2>

    <p class="intro call-to-action">Why not bug them about that?</p>
  </article>

<% end %>

app/views/votes/show.html.erb
<article>
  <h1>Thanks! Your vote helps us improve the data.</h1>

  <p class="intro call-to-action"><%= link_to "Return to #{@type_of_thing.name.pluralize}", type_of_thing_path(@type_of_thing.name.pluralize.downcase) %></p>
</article>